@server = http://localhost:4004
### ------------------------------------------------------------------------
### Customers Management

###
# GET a list of Business Partners
###
GET {{server}}/manage/Customers

###
# POST a specific Business Partner
###
POST {{server}}/manage/Customers
Content-Type: application/json
Accept: application/json

{ "CategoryCode": "1", "FirstName": "Blint", "LastName": "Stones" }