@server = http://localhost:4004
# @server = https://bookcatalog-c58d60d8trial.cfapps.us10.hana.ondemand.com
@me = Authorization: Basic {{$processEnv USER}}:

### ------------------------------------------------------------------------
### Service Metadata Origin

### Service Document
GET {{server}}/browse

### Service $metadata document
GET {{server}}/browse/$metadata

### ------------------------------------------------------------------------
### Books Management

### Browsing Books
GET {{server}}/browse/Books?
# &$select=title,author
# &$expand=currency
# &sap-language=de

### ------------------------------------------------------------------------
### Authors Management

### Browsing Authors
GET {{server}}/manage/Authors?
# &$select=name,dateOfBirth,placeOfBirth
# &$expand=books($select=title;$expand=currency)
# &$filter=ID eq 101
# &sap-language=de

### ------------------------------------------------------------------------
# Submit Order as authenticated user
# (send that three times to get out-of-stock message)
POST {{server}}/browse/submitOrder
Content-Type: application/json

{ "book":201, "amount":5 }

### Browsing Book 201
GET {{server}}/browse/Books(201)
# &$select=title,author
# &$expand=currency
# &sap-language=de
### Browsing Authors

### Deep Expansion
GET {{server}}/manage/Orders?$expand=Items($expand=book)

### ------------------------------------------------------------------------
### Orders Management

###
# Get Orders
GET {{server}}/manage/Orders?$filter=customer eq '1000175'
# &$expand=Items

### ------------------------------------------------------------------------
### Customers Management

###
# GET a list of Business Partners
# Scenario A or B
###
GET {{server}}/manage/Customers

###
# POST a specific Business Partner
###
POST {{server}}/manage/Customers
Content-Type: application/json
Accept: application/json

{
    "BusinessPartner": "fb1d21f9-0374-44ea-b45f-4a23ac4fcab2",
    "FirstName": "amazonjt23",
    "LastName": "Bootcamp",
    "BusinessPartnerCategory":"1"
}