# @server = http://localhost:4004
@server = https://bookcatalog-8221c96ftrial.cfapps.eu10.hana.ondemand.com
### ------------------------------------------------------------------------
### Customers Management

###
# GET a list of Business Partners
###
GET {{server}}/manage/Customers

###
# POST a specific Business Partner
###
POST {{server}}/manage/Customers
Content-Type: application/json
Accept: application/json

{ "CategoryCode": "1", "FirstName": "Zlint", "LastName": "Stones" }